### ISSUE TITLE
Having trouble installing rux-rails

### ISSUE THREAD

**Issue by mateomurphy** [camertron/rux-rails#15] opened 2023-06-04 16:38 UTC
I've run into a few issues getting rux-rails to work.

First, if I put the gem in `development` only, components don't get transpiled when running rspec. But if I add it to the `test` group as well, I run into the following error:

```
Failure/Error: require File.expand_path('../config/environment', __dir__)

NoMethodError:
  undefined method `gsub' for #<Pathname:0x00007fccc65b6248>
  Did you mean?  sub
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/file_update_checker.rb:153:in `escape'
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/file_update_checker.rb:147:in `block in compile_glob'
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/file_update_checker.rb:146:in `each'
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/file_update_checker.rb:146:in `map'
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/file_update_checker.rb:146:in `compile_glob'
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/file_update_checker.rb:48:in `initialize'
# /.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/rux-rails-1.3.0/lib/rux-rails/railtie.rb:52:in `new'
```

Finally, if I leave the gem in `development`, but transpile (by loading the component in the rails console, for example), I get an error in the transpiled component: `uninitialized constant Rux` etc. Should I be adding the regular `rux` gem in all environments?

**Comment by camertron** [comment] 2023-06-04 20:44
Hey @mateomurphy, thanks for bringing this to my attention. Unfortunately I haven't been able to reproduce either problem. Are you able to share your app with me so I can debug further? If not, then a reproducible test repo would really help too.

Using rux with RSpec worked as expected, and I was able to execute `require 'component'` in a Rails console without issue.

**Comment by mateomurphy** [comment] 2023-06-04 21:11
Thanks for the reply, I'll try to set up a test repo that reproduces the error and let you know

**Comment by mateomurphy** [comment] 2023-06-05 00:27
Ok, turns out the `NoMethodError` was due to our codebase doing `config.eager_load_paths << Rails.root.join(item}`, which usually works but not with the `ActiveSupport::FileUpdateChecker`.

However the other two points still seem to stand, and you can see it in the test repo I added here: https://github.com/mateomurphy/rux-rails-test

Running `bundle exec rspec spec`, the component under test will not transpile, unless `rux-rails` is also added to the test group. This seems to be normal, but doesn't match what the documentation says.

**Comment by camertron** [comment] 2023-06-05 04:36
Ah ok, glad you were able to track down the cause of the `NoMethodError`.

> Running `bundle exec rspec spec`, the component under test will not transpile, unless `rux-rails` is also added to the test group. This seems to be normal, but doesn't match what the documentation says.

Right, rux-rails should be added to the test group in order to be available in tests. I clearly didn't think about testing when I wrote the docs! I'll go ahead and update the README. Come to think of it, rux-rails should probably be available in production environments too so the `rux:transpile` rake task is available. I'll re-word the docs.

> However the other two points still seem to stand.

After adding rux-rails to the test and development groups, I was able to get the tests to pass. Referencing the component in a rails console also seems to work as expected.

**Comment by mateomurphy** [comment] 2023-06-07 13:23
Great! Speaking of `rux:transpile`, what is considered the best practice regarding version control and the transpiled components? Should they be checked in?

**Comment by camertron** [comment] 2023-06-08 03:32
Good question. I always .gitignore the transpiled component files and don't check them into source control. They should however be part of your build artifact, eg. gem, Docker image, etc.

**Comment by camertron** [comment] 2023-06-18 04:42
Hey @mateomurphy I'm going to close this for now. Feel free to reopen if you're still running into issues.

**Closed as completed by camertron** 2023-06-18 04:42 UTC
